{% set name = "auto-labeling-pipeline" %}
{% set version = "0.1.23" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/auto-labeling-pipeline-{{ version }}.tar.gz
  sha256: 8a0f15e275bda0c1f5cadd24bb58ba447f5593b38eb4eee6d18d420eca2c944c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - boto3
    - jinja2
    - pydantic
    - python >=3.6
    - requests

test:
  imports:
    - auto_labeling_pipeline
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
    - vcrpy
  source_files:
    - tests

about:
  home: https://github.com/doccano/auto-labeling-pipeline
  summary: Auto labeling pipeline for doccano
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
